# Generated by Django 2.2.16 on 2023-06-04 10:36

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230604_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[api.validators.validate_hex_color], verbose_name='Цвет HEX'),
        ),
    ]
